/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MSQLTypesUiModule extends AbstractMSQLTypesUiModule {

	public MSQLTypesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
