/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query.scoping;

import org.mdse.minisql.types.scoping.MSQLTypesScopeProvider;

public abstract class AbstractMSQLQueryScopeProvider extends MSQLTypesScopeProvider {
}
