/*
 * generated by Xtext 2.26.0
 */
package pizzacution.query.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class QueryLanguageStandaloneSetup extends QueryLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new QueryLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
