/*
 * generated by Xtext 2.26.0
 */
package pizzacution.schema.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LanguageUiModule extends AbstractLanguageUiModule {

	public LanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
