/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.mdse.minisql.types.parser.antlr.internal.InternalMSQLTypesParser;
import org.mdse.minisql.types.services.MSQLTypesGrammarAccess;

public class MSQLTypesParser extends AbstractAntlrParser {

	@Inject
	private MSQLTypesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMSQLTypesParser createParser(XtextTokenStream stream) {
		return new InternalMSQLTypesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Type";
	}

	public MSQLTypesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MSQLTypesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
