/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MSQLTypesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/mdse/minisql/types/parser/antlr/internal/InternalMSQLTypes.tokens");
	}
}
