/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.query;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.mdse.minisql.query.converters.MSQLQueryTerminalConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MSQLQueryRuntimeModule extends AbstractMSQLQueryRuntimeModule {
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
    	return MSQLQueryTerminalConverter.class;
    }
}
