/*
 * generated by Xtext 2.26.0
 */
package pizzacution.query.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class QueryLanguageUiModule extends AbstractQueryLanguageUiModule {

	public QueryLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
