<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="types" nsURI="http://mdse.org/minisql/types" nsPrefix="minisqltypes">
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="UndefinedType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true">
    <eOperations name="getType" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
</ecore:EPackage>
