/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mdse.minisql.types.MSQLTypesRuntimeModule;
import org.mdse.minisql.types.MSQLTypesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MSQLTypesIdeSetup extends MSQLTypesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MSQLTypesRuntimeModule(), new MSQLTypesIdeModule()));
	}
	
}
