/*
 * generated by Xtext 2.26.0
 */
package pizzacution.query.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pizzacution.query.dsl.QueryLanguageRuntimeModule;
import pizzacution.query.dsl.QueryLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class QueryLanguageIdeSetup extends QueryLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QueryLanguageRuntimeModule(), new QueryLanguageIdeModule()));
	}
	
}
