/*
 * generated by Xtext 2.26.0
 */
package pizzacution.schema.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LanguageStandaloneSetup extends LanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new LanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
