/*
 * generated by Xtext 2.26.0
 */
package pizzacution.schema.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends AbstractLanguageRuntimeModule {
}
