/**
 * generated by Xtext 2.26.0
 */
package pizzacution.query.dsl.formatting2;

import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class LanguageFormatter extends AbstractFormatter2 {
  protected void _format(final /* SelectQuery */Object selectQuery, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nwhatClause cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nthatClause cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final /* ThatClause */Object thatClause, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nthatDirective cannot be resolved"
      + "\nformat cannot be resolved");
  }
  
  public void format(final Object selectQuery, final IFormattableDocument document) {
    if (selectQuery instanceof XtextResource) {
      _format((XtextResource)selectQuery, document);
      return;
    } else if (selectQuery instanceof EObject) {
      _format((EObject)selectQuery, document);
      return;
    } else if (selectQuery == null) {
      _format((Void)null, document);
      return;
    } else if (selectQuery != null) {
      _format(selectQuery, document);
      return;
    } else if (selectQuery != null) {
      _format(selectQuery, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(selectQuery, document).toString());
    }
  }
}
