/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMSQLTypesScopeProvider extends DelegatingScopeProvider {
}
