/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.mdse.minisql.types.validation.MSQLTypesValidator;

public abstract class AbstractMSQLSchemaValidator extends MSQLTypesValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://mdse.org/minisql/schema"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://mdse.org/minisql/types"));
		return result;
	}
}
