/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.types;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MSQLTypesStandaloneSetup extends MSQLTypesStandaloneSetupGenerated {

	public static void doSetup() {
		new MSQLTypesStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
