/*
 * generated by Xtext 2.20.0
 */
package org.mdse.minisql.schema.scoping;

import org.mdse.minisql.types.scoping.MSQLTypesScopeProvider;

public abstract class AbstractMSQLSchemaScopeProvider extends MSQLTypesScopeProvider {
}
