/*
 * generated by Xtext 2.26.0
 */
package pizzacution.query.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pizzacution.query.dsl.LanguageRuntimeModule;
import pizzacution.query.dsl.LanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LanguageIdeSetup extends LanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LanguageRuntimeModule(), new LanguageIdeModule()));
	}
	
}
